#specifies the URL for connecting to the PostgreSQL database
#indicates that the database is running on localhost at port 5432 and the database name is glowtime
spring.datasource.url=jdbc:postgresql://localhost:5432/glowtime
#my username
spring.datasource.username=rameenamin
#no set password
spring.datasource.password=
#hibernate will automatically update or create the database scheme based on my entity classes
spring.jpa.hibernate.ddl-auto=update
#specifies which dialect to use,, use the PostgreSQLDialect for PostgreSQL databases.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#spring bot will run on port 800
server.port=8080
